### ISSUE TITLE
(feat) optional only output index files

### ISSUE THREAD

**Issue by markbref** [hellotoby/metalsmith-to-json#2]
Hi, just started playing with this plugin for a project :smile:

For my project, I don't need all the single files that is also created though, but only the index files to act as a static json "db".

I was thinking this could be implemented with a simple `onlyOutputIndex: true` option, that is set to true, then simply delete all the single files from that `indexPath` in the files array.

What do you think?

**Comment by markbref** [comment]
Sent you a PR :wink:

**Comment by hellotoby** [comment]
Looks good. PR merged :)
